export const Avatar = [
  {
    name: "Tolamise",
    msg: "You are welcome. I think dough...",
    time: "10:30 PM",
    num: 6,
    img: require("../../assets/images/avatar1.jpg"),
  },
  {
    name: "Ephraim",
    msg: "Yes, boss. I still day Ife o.",
    time: "10:10 PM",
    num: 1,
    img: require("../../assets/images/avatar2.jpg"),
  },
  {
    name: "Ifeyinwa",
    msg: "I'm only checking out on you. What have you...",
    time: "8:30 PM",
    num: 2,
    img: require("../../assets/images/avatar3.jpg"),
  },
  {
    name: "Small Winch",
    msg: "Lol. You way we no day see...",
    time: "8:20 PM",
    num: 4,
    img: require("../../assets/images/avatar4.jpg"),
  },
  {
    name: "Austino",
    msg: "Drop account, make I reason...",
    time: "8:15 PM",
    num: 3,
    img: require("../../assets/images/avatar5.jpg"),
  },
  {
    name: "Big Bro",
    msg: "I go drop you gig now. You sabi...",
    time: "7:30 PM",
    num: 5,
    img: require("../../assets/images/avatar6.jpg"),
  },
  {
    name: "Tola",
    msg: "Na on to say e never click...",
    time: "4:30 PM",
    num: 1,
    img: require("../../assets/images/avatar7.jpg"),
  },
  {
    name: "Person Babe",
    msg: "When are you visiting? Boys...",
    time: "3:30 PM",
    num: 2,
    img: require("../../assets/images/avatar8.jpg"),
  },
  {
    name: "Side Chick",
    msg: "You are welcome. Try day sleep...",
    time: "12:30 PM",
    num: 1,
    img: require("../../assets/images/avatar9.jpg"),
  },
  {
    name: "Ise baby",
    msg: "Lol. I have a boyfriend...",
    time: "12:30 PM",
    num: 6,
    img: require("../../assets/images/avatar10.jpg"),
  },
  {
    name: "Godwin",
    msg: "Yes. I Understand how...",
    time: "10:30 AM",
    num: 6,
    img: require("../../assets/images/avatar11.jpg"),
  },
];
